const baseUrl = "https://localhost:7229/api/";
export const PortfoliosURL = baseUrl + "portfolio/getall/";
export const ProjectsURL = baseUrl + "project/getall/";
export const singlePortfolio = baseUrl + "portfolio/get/"
export const singleProject = baseUrl + "project/get/"
export const CreatePortfolioURL = baseUrl + "portfolio/create/";
export const LoginPortURL = baseUrl + "login/logport";
export const portSingle = baseUrl + "portfolio/getsingle/";
export const CreateProject = baseUrl + "project/create";
export const DeletePort = baseUrl + 'portfolio/delete/';
export const DeleteProj = baseUrl + 'project/delete/';
